// <auto-generated />
using MODELO.Desafio.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MODELO.Desafio.DAL.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("MODELO.Desafio.DAL.Interface.Entities.Fair", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("District");

                    b.Property<string>("NameFair")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NameFair");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Neighborhood");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Region");

                    b.HasKey("Id");

                    b.ToTable("Fair");
                });
#pragma warning restore 612, 618
        }
    }
}
